version: "3.7"

services:
  postgres:
    image: postgres
    container_name: db
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employee
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: ./DockerFile
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - postgres

networks:
  app-network:
    driver: bridge