FROM openjdk:11

VOLUME /tmp

# Add application JAR
COPY peopleflow-1.0.0-SNAPSHOT.jar app.jar

EXPOSE 8080

# Start application
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
